Revert "Use correct sdist/build_ext modules"
This reverts commit 21a917bfa9854b66c34f7f7f33907422a2a331d2.

Will get "AttributeError: 'Extension' object has no attribute '_needs_stub'"
otherwise